#ifndef ERROR_H
#define ERROR_H
#include <stddef.h>

typedef enum ErrorKind {
    ERROR_NONE,
    
    ERROR_DIV_BY_ZERO,
    ERROR_UNEXPECTED_CONTINUE,
    ERROR_UNEXPECTED_BREAK,
    ERROR_UNEXPECTED_RETURN,
    ERROR_NOT_DEFINED,
    ERROR_CANNOT_ASSIGN_TO_CONST,
    ERROR_CANNOT_REASSIGN_CONST,
    ERROR_CANNOT_REDEFINE_CONST,
    ERROR_CANNOT_REDEFINE_FUNC,
    ERROR_CANNOT_REDEFINE_STRUCT,
    ERROR_CANNOT_REDEFINE_ENUM,
    ERROR_CANNOT_TAKE_REF_TO_RVAL,
    ERROR_OUT_OF_BOUNDS,

    ERROR_BREAK_OUTSIDE_LOOP,
    ERROR_CONTINUE_OUTSIDE_LOOP,

    ERROR_TOO_FEW_ARGS,
    ERROR_TOO_MANY_ARGS,
    ERROR_RECURSION_LIMIT_EXCEEDED,
    ERROR_UNEXPECTED_NAMED_ARG,
    ERROR_FORMAT_MISMATCHES_VA_ARGS_COUNT,
    ERROR_ARGS_AFTER_NAMED_VA_ARG,
    ERROR_WRONG_FORMAT_STR,

    ERROR_INCOMPATIBLE_TYPES,

    ERROR_UNKNOWN_TYPE,
    ERROR_UNKNOWN_FIELD,
    ERROR_MULTIPLE_INITIALIZERS,
    
    ERROR_CLOSED_STDIN,
} RuntimeError;

typedef struct {
    RuntimeError *items;
    size_t count;
    size_t capacity;
} Errors;

#endif // ERROR_H