#ifndef PARSER_ERROR_H
#define PARSER_ERROR_H

typedef enum ParserError {
    PERROR_NONE,
    
    PERROR_WRONG_NUMBER_FORMAT,
    PERROR_VALUE_OUT_OF_RANGE,

    PERROR_UNMATCHED_PAREN,
    PERROR_UNEXPECTED_TOKEN,
    PERROR_UNEXPECTED_EOF,

    PERROR_EMPTY_CHAR_LIT,
    PERROR_MULTI_CHARACTER_CHAR_LIT,

    PERROR_WRONG_FIELD_NAME_FORMAT,
    PERROR_WRONG_INITIALIZER_OBJECT,
    PERROR_MULTIPLE_INITIALIZERS,
    
    PERROR_MULTIPLE_ARGS,
    PERROR_ARGS_AFTER_VA_ARG,
} ParserError;

#endif //PARSER_ERROR_H
